"""add categoria_id foreign key

Revision ID: f0494fd0c49c
Revises: 
Create Date: 2025-07-14 14:04:34.844088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0494fd0c49c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
with op.batch_alter_table('atletas') as batch_op:
    batch_op.create_foreign_key('fk_atletas_categoria_id', 'categorias', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    # ### end Alembic commands ###
